- name: variable
  hosts: localhost
  vars: 
    course: "ansible"
    trainer: "sam"
    duration: "120hrs"
  tasks:
  - name: print what i want
    ansible.builtin.debug:
      msg: "hi, we are learning {{course}} frpm trainer {{trainer}}, duration is {{duration}}."